nodeLinker: node-modules

enableGlobalCache: true

compressionLevel: mixed

nmMode: hardlinks-local

preferInteractive: true

enableTelemetry: false

logFilters:
  - code: YN0013
    level: discard

enableImmutableInstalls: false
