/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manga": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search manga */
        get: operations["searchManga"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manga/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all manga with pagination */
        get: operations["getAllManga"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manga/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get manga by ID */
        get: operations["getMangaById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user's manga library */
        get: operations["getLibrary"];
        put?: never;
        /** Add manga to library */
        post: operations["addToLibrary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/progress/{manga_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get progress for specific manga */
        get: operations["getProgress"];
        /** Update reading progress */
        put: operations["updateProgress"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        APIResponse: {
            success: boolean;
            data?: Record<string, never>;
            error?: components["schemas"]["APIError"];
            meta?: components["schemas"]["Meta"];
        };
        APIError: {
            /** @example BAD_REQUEST */
            code: string;
            /** @example Invalid request body */
            message: string;
        };
        Meta: {
            total?: number;
            count?: number;
            limit?: number;
            offset?: number;
            has_more?: boolean;
            page?: number;
            total_pages?: number;
        };
        ErrorResponse: components["schemas"]["APIResponse"] & {
            /** @example false */
            success?: boolean;
        };
        MessageResponse: components["schemas"]["APIResponse"] & {
            /** @example true */
            success?: boolean;
            data?: {
                message?: string;
            };
        };
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            created_at: string;
        };
        UserRegisterRequest: {
            /** @example manga_lover */
            username: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /**
             * Format: password
             * @example securepassword123
             */
            password: string;
        };
        UserLoginRequest: {
            /** @example manga_lover */
            username: string;
            /**
             * Format: password
             * @example securepassword123
             */
            password: string;
        };
        AuthResponse: components["schemas"]["APIResponse"] & {
            /** @example true */
            success?: boolean;
            data?: {
                user: components["schemas"]["User"];
                /** @description JWT access token */
                token: string;
            };
        };
        UserProfileResponse: components["schemas"]["APIResponse"] & {
            data?: {
                user?: components["schemas"]["User"];
            };
        };
        /** @enum {string} */
        MangaStatus: "ongoing" | "completed" | "hiatus" | "cancelled";
        Manga: {
            id: string;
            title: string;
            author?: string;
            genres?: string[];
            status?: components["schemas"]["MangaStatus"];
            total_chapters?: number;
            description?: string;
            /** Format: uri */
            cover_image_url?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        MangaListResponse: components["schemas"]["APIResponse"] & {
            data?: {
                items?: components["schemas"]["Manga"][];
            };
        };
        MangaDetailResponse: components["schemas"]["APIResponse"] & {
            data?: {
                manga?: components["schemas"]["Manga"];
            };
        };
        /** @enum {string} */
        ReadingStatus: "reading" | "completed" | "plan_to_read" | "on_hold" | "dropped";
        UserProgress: {
            user_id: string;
            manga_id: string;
            current_chapter: number;
            status: components["schemas"]["ReadingStatus"];
            rating?: number | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            updated_at?: string;
        };
        UserProgressWithManga: components["schemas"]["UserProgress"] & {
            manga?: components["schemas"]["Manga"];
        };
        LibraryAddRequest: {
            manga_id: string;
            status: components["schemas"]["ReadingStatus"];
            /** @default 0 */
            current_chapter: number;
        };
        ProgressUpdateRequest: {
            current_chapter: number;
            status?: components["schemas"]["ReadingStatus"];
            rating?: number;
        };
        LibraryResponse: components["schemas"]["APIResponse"] & {
            data?: {
                items?: components["schemas"]["UserProgressWithManga"][];
            };
        };
        ProgressResponse: components["schemas"]["APIResponse"] & {
            data?: {
                progress?: components["schemas"]["UserProgress"];
            };
        };
        /** @enum {string} */
        TCPMessageType: "auth" | "auth_success" | "auth_failed" | "ping" | "pong" | "progress" | "broadcast" | "error";
        TCPMessage: {
            type: components["schemas"]["TCPMessageType"];
            /** Format: date-time */
            timestamp: string;
            data?: Record<string, never>;
        };
        TCPAuthMessage: {
            token: string;
        };
        TCPAuthSuccessMessage: {
            user_id?: string;
            username?: string;
            message?: string;
        };
        TCPAuthFailedMessage: {
            reason?: string;
        };
        TCPProgressMessage: {
            manga_id: string;
            current_chapter: number;
            status?: components["schemas"]["ReadingStatus"];
            rating?: number;
        };
        TCPProgressBroadcast: {
            user_id?: string;
            username?: string;
            manga_id?: string;
            manga_title?: string;
            current_chapter?: number;
            status?: components["schemas"]["ReadingStatus"];
            /** Format: date-time */
            timestamp?: string;
        };
        TCPErrorMessage: {
            code?: string;
            message?: string;
        };
        /** @enum {string} */
        UDPMessageType: "register" | "unregister" | "ping" | "register_success" | "register_failed" | "pong" | "notification" | "error";
        UDPMessage: {
            type: components["schemas"]["UDPMessageType"];
            /** Format: date-time */
            timestamp: string;
            data?: Record<string, never>;
        };
        UDPRegisterMessage: {
            /** @description Unique client identifier */
            client_id: string;
            user_id?: string;
            username?: string;
        };
        UDPRegisterSuccessMessage: {
            client_id?: string;
            message?: string;
        };
        UDPRegisterFailedMessage: {
            reason?: string;
        };
        UDPUnregisterMessage: {
            client_id: string;
        };
        UDPNotification: {
            manga_id: string;
            manga_title: string;
            chapter_number: number;
            chapter_title?: string;
            /** Format: date-time */
            release_date: string;
            /** @example New chapter released! */
            message: string;
        };
        UDPPingMessage: {
            /** Format: date-time */
            client_time?: string;
        };
        UDPPongMessage: {
            /** Format: date-time */
            server_time?: string;
            /** Format: date-time */
            client_time?: string;
        };
        UDPErrorMessage: {
            code?: string;
            message?: string;
        };
        /** @enum {string} */
        ChatMessageType: "join" | "leave" | "message" | "system" | "error";
        ChatMessage: {
            type: components["schemas"]["ChatMessageType"];
            user_id?: string;
            username?: string;
            content?: string;
            room?: string;
            /** Format: date-time */
            timestamp: string;
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Number of items to return */
        Limit: number;
        /** @description Number of items to skip */
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegisterRequest"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    searchManga: {
        parameters: {
            query?: {
                /** @description Search by title */
                title?: string;
                /** @description Filter by author */
                author?: string;
                /** @description Filter by genre */
                genre?: string;
                /** @description Filter by status */
                status?: components["schemas"]["MangaStatus"];
                /** @description Number of items to return */
                limit?: components["parameters"]["Limit"];
                /** @description Number of items to skip */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MangaListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getAllManga: {
        parameters: {
            query?: {
                /** @description Number of items to return */
                limit?: components["parameters"]["Limit"];
                /** @description Number of items to skip */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All manga */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MangaListResponse"];
                };
            };
        };
    };
    getMangaById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Manga ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Manga details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MangaDetailResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User's library */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    addToLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryAddRequest"];
            };
        };
        responses: {
            /** @description Manga added to library */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manga_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reading progress */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manga_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgressUpdateRequest"];
            };
        };
        responses: {
            /** @description Progress updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
